### ISSUE TITLE
Plugin not initialised correctly

### ISSUE THREAD

**Issue by jazen** [rogeliog/jest-watch-select-projects#4]
I'm using `jest v23.5.0` and added some debug output to `node_modules/jest-watch-select-projects/build/index.js`:

```
class JestPluginProjects {
  constructor() {
    console.log('ctor')
    this._activeProjects = {};
  }

  apply(jestHook) {
    console.log('apply jest hooks')
    ...
```

And realized the `apply` method isn't called at all:

```
npm t -- --watch --no-cache

> NODE_ENV=test jest "--watch" "--no-cache"

ctor
TypeError: Cannot read property 'length' of undefined
    at JestPluginProjects._getActiveProjectsText (/Users/<redacted>/node_modules/jest-watch-select-projects/build/index.js:72:44)
    at JestPluginProjects.getUsageInfo (/Users/<redacted>/node_modules/jest-watch-select-projects/build/index.js:87:52)
...
```

**Comment by kentcdodds** [comment]
cc @rogeliog
